name: 'Snyk Issues to GH Issues'
description: 'create a github issue for snyk issues'
inputs:
  sarif-file:  # ID of input
    description: 'sarif output file contain snyk issues'
    required: true
    default: 'snyk.sarif'
#outputs:
#  issue: # id of output
#    description: 'The issue object as a JSON string'
runs:
  using: 'node16'
  main: 'dist/index.js'