name: snyk-labs action example - Snyk Issues to Github Issues
on: 
  # - push
  workflow_dispatch:
jobs:
  security:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/workflows/snyk-with-github-issues
    steps:
      - uses: actions/checkout@v2
      - uses: snyk/actions/setup@master
      - uses: actions/setup-go@v1
        with:
          go-version: "1.16"
      - name: print env
        run: env
      - name: snyk test
        run: snyk test --sarif-file-output=../../../snyk.sarif
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - uses: ./sarif-to-gh-issues
        with:
          sarif_file: snyk.sarif
        env:
          GITHUB_TOKEN: ${{ github.token }}
          REMOTE_REPO_URL: ${{ github.repositoryUrl }}
          
