name: snyk-labs action example - Snyk Issues to Github Issues
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: issues-to-github-issues
    steps:
      - uses: actions/checkout@v2
      - uses: snyk/actions/setup@master
      - name: Snyk monitor
        run: snyk test --sarif-file-output=snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - uses: ./issues-to-github-issues
        with:
          sarif-file: snyk.sarif
          