name: snyk-labs action example - Snyk Issues to Github Issues
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ../snyk-issues-to-github-issues
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Snyk monitor
        run: snyk test --sarif-file-output=snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - uses: ./snyk-issues-to-github-issues
        with:
          sarif-file: snyk.sarif
          